name: multiverse_guide
description: "Guia do Multiverso - Rick and Morty"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  cached_network_image: ^3.3.0
  get_it: ^7.6.4
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.5
  mockito: ^5.4.2
  build_runner: ^2.4.6
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
